# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastpragma',
                'doc_host': 'https://risheekkumarb.github.io',
                'git_url': 'https://github.com/risheekkumarb/fastpragma',
                'lib_path': 'fastpragma'},
  'syms': {'fastpragma.core': {'fastpragma.core.foo': ('core.html#foo', 'fastpragma/core.py')}}}
