# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_dataloader.ipynb.

# %% auto #0
__all__ = ['path', 'max_profile_toks', 'max_lifelong_toks', 'max_events', 'max_event_toks', 'max_tokens', 'batch_fields',
           'special_toks', 'user_rec', 'rec_ntoks', 'pack_batch', 'PRAGMADataLoader', 'mask_batch', 'split_shards',
           'pragma_dl', 'pragma_dls', 'batch_shapes']

# %% ../nbs/02_dataloader.ipynb #afb8b154
from .data import DataSource, Tokenizer, PRAGMADataset
import polars as pl
from fastai.data.external import untar_data, URLs
from fastcore.all import *

path = untar_data(URLs.ML_100k)

# %% ../nbs/02_dataloader.ipynb #35ae5fc0
import torch
from torch.utils.data import IterableDataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

# %% ../nbs/02_dataloader.ipynb #aa65d87d
max_profile_toks,max_lifelong_toks,max_events,max_event_toks,max_tokens = 200,64,6500,24,12000

# %% ../nbs/02_dataloader.ipynb #ac2dcf61
def _tok(df):
    if len(df)==0: return torch.empty(0,3,dtype=torch.long),torch.empty(0,dtype=torch.float32)
    return torch.tensor(df.select('key_id','val_id','val_pos').to_numpy(), dtype=torch.long),torch.tensor(df['logsec'].to_numpy(), dtype=torch.float32)

def _pad(xs, val=0):
    if len(xs)==0: return torch.empty(0,0,3,dtype=torch.long),torch.empty(0,0,dtype=torch.bool)
    lens = torch.tensor([len(o) for o in xs])
    return pad_sequence(xs, batch_first=True, padding_value=val),torch.arange(lens.max())[None,:] < lens[:,None]

# %% ../nbs/02_dataloader.ipynb #ef4beadb
def user_rec(df):
    uid = df['user_id'][0]
    prof = df.filter((pl.col('event_idx')<0) & (pl.col('time')==0)).head(max_profile_toks)
    ll = df.filter((pl.col('event_idx')<0) & (pl.col('time')!=0)).tail(max_lifelong_toks)
    ev = df.filter(pl.col('event_idx')>=0).sort('event_idx')
    ev_ids = ev.select('event_idx').unique(maintain_order=True).tail(max_events)['event_idx'].to_list()
    ev = ev.filter(pl.col('event_idx').is_in(ev_ids))
    pt,ptm = _tok(prof)
    lt,ltm = _tok(ll)
    ets,etm,cal = [],[],[]
    for _,g in ev.partition_by('event_idx', as_dict=True, maintain_order=True).items():
        g = g.head(max_event_toks)
        t,tm = _tok(g)
        ets.append(t); etm.append(tm[0] if len(tm) else torch.tensor(0.))
        cal.append(torch.tensor(g.select('hour','dow','dom').row(0), dtype=torch.float32))
    return dict(uid=uid, profile=pt, profile_time=ptm, lifelong=lt, lifelong_time=ltm, events=ets, event_time=torch.stack(etm) if etm else torch.empty(0), cal=torch.stack(cal) if cal else torch.empty(0,3))

# %% ../nbs/02_dataloader.ipynb #34773b8d
def rec_ntoks(o): return len(o['profile']) + len(o['lifelong']) + sum(len(e) for e in o['events'])

# %% ../nbs/02_dataloader.ipynb #7730d987
def pack_batch(recs):
    prof,prof_mask = _pad([o['profile'] for o in recs])
    ll,ll_mask = _pad([o['lifelong'] for o in recs])
    ptime = pad_sequence([o['profile_time'] for o in recs], batch_first=True)
    ltime = pad_sequence([o['lifelong_time'] for o in recs], batch_first=True)
    ets,eu,etime,cal,hoffs = [],[],[],[],[0]
    for i,o in enumerate(recs):
        ets += o['events']; eu += [i]*len(o['events'])
        etime.append(o['event_time']); cal.append(o['cal'])
        hoffs.append(hoffs[-1] + len(o['events']) + 1)
    lens = torch.tensor([len(o) for o in ets], dtype=torch.long)
    eoffs = torch.cat([torch.tensor([0]), lens.cumsum(0)]) if len(lens) else torch.tensor([0])
    etoks = torch.cat(ets) if len(ets) else torch.empty(0,3,dtype=torch.long)
    etime = torch.cat(etime) if len(etime) else torch.empty(0)
    cal = torch.cat(cal) if len(cal) else torch.empty(0,3)
    return dict(profile=prof, profile_mask=prof_mask, profile_time=ptime, lifelong=ll, lifelong_mask=ll_mask, lifelong_time=ltime, event_tokens=etoks, event_offsets=eoffs, event_user=torch.tensor(eu), event_time=etime, cal=cal, history_offsets=torch.tensor(hoffs), uids=[o['uid'] for o in recs])

# %% ../nbs/02_dataloader.ipynb #2eaef53e
class PRAGMADataLoader(IterableDataset):
    def __init__(self, shards, max_tokens=max_tokens, shuffle=False):
        store_attr('shards,max_tokens,shuffle')
    def __iter__(self):
        paths = list(self.shards)
        if self.shuffle: paths = L(paths).shuffle()
        batch,ntoks = [],0
        for p in paths:
            df = pl.read_parquet(p)
            for g in df.partition_by('user_id', maintain_order=True):
                r = user_rec(g)
                n = rec_ntoks(r)
                if batch and ntoks+n>self.max_tokens:
                    yield pack_batch(batch)
                    batch,ntoks = [],0
                batch.append(r); ntoks += n
        if batch: yield pack_batch(batch)

# %% ../nbs/02_dataloader.ipynb #e719ba09
@patch
def __len__(self:PRAGMADataLoader):
    if hasattr(self, '_len'): return self._len
    batch,ntoks,n_batches = [],0,0
    for p in self.shards:
        df = pl.read_parquet(p)
        for g in df.partition_by('user_id', maintain_order=True):
            r = user_rec(g)
            n = rec_ntoks(r)
            if batch and ntoks+n>self.max_tokens:
                n_batches += 1
                batch,ntoks = [],0
            batch.append(r); ntoks += n
    self._len = n_batches + bool(batch)
    return self._len

# %% ../nbs/02_dataloader.ipynb #d0c7694d
def _vocab_id(vocab, *names):
    for n in names:
        if n in vocab: return vocab[n]
    raise KeyError(f"missing vocab token: {names}")

# %% ../nbs/02_dataloader.ipynb #1413097c
def mask_batch(b, tok, p_tok=.15, p_event=.10, p_key=.10, p_unk=.05, ignore=-100):
    x = b['event_tokens'].clone()
    n = len(x)
    y = torch.full((n,), ignore, dtype=torch.long)
    if n == 0:
        b = b.copy()
        b['event_tokens'],b['event_labels'],b['mlm_mask'] = x,y,y != ignore
        return b

    mask_id = _vocab_id(tok.val_vocab, '[MASK]', '<MASK>', '[mask]', '<mask>')
    unk_id = _vocab_id(tok.val_vocab, '[UNK]', '<UNK>', '[unk]', '<unk>')
    lens = b['event_offsets'][1:] - b['event_offsets'][:-1]
    tev = torch.repeat_interleave(torch.arange(len(lens)), lens)
    tu = b['event_user'][tev]
    nk = max(tok.key_vocab.values()) + 1

    m = torch.rand(n) < p_tok
    m |= (torch.rand(len(lens)) < p_event)[tev]
    m |= (torch.rand(len(b['uids']), nk) < p_key)[tu, x[:,0]]

    y[m] = x[m,1]
    u = m & (torch.rand(n) < p_unk)
    x[m & ~u,1] = mask_id
    x[u,1] = unk_id
    y[u] = ignore

    b = b.copy()
    b['event_tokens'],b['event_labels'],b['mlm_mask'] = x,y,y != ignore
    return b

# %% ../nbs/02_dataloader.ipynb #7eaab775
def split_shards(shards, valid_pct=.2):
    n = max(1, round(len(shards)*valid_pct))
    return shards[:-n],shards[-n:]

# %% ../nbs/02_dataloader.ipynb #57e56f58
class PRAGMADataLoader(IterableDataset):
    def __init__(self, shards, max_tokens=max_tokens, shuffle=False, tok=None, mask=False):
        store_attr('shards,max_tokens,shuffle,tok,mask')
    def _paths(self):
        paths = list(self.shards)
        if self.shuffle: paths = L(paths).shuffle()
        wi = torch.utils.data.get_worker_info()
        return paths if wi is None else paths[wi.id::wi.num_workers]
    def __iter__(self):
        batch,ntoks = [],0
        for p in self._paths():
            df = pl.read_parquet(p)
            for g in df.partition_by('user_id', maintain_order=True):
                r = user_rec(g); n = rec_ntoks(r)
                if batch and ntoks+n>self.max_tokens:
                    b = pack_batch(batch)
                    yield mask_batch(b, self.tok) if self.mask else b
                    batch,ntoks = [],0
                batch.append(r); ntoks += n
        if batch:
            b = pack_batch(batch)
            yield mask_batch(b, self.tok) if self.mask else b

# %% ../nbs/02_dataloader.ipynb #bed9542a
def pragma_dl(shards, max_tokens=max_tokens, shuffle=False, tok=None, mask=False, num_workers=0):
    return DataLoader(PRAGMADataLoader(shards, max_tokens, shuffle, tok, mask), batch_size=None, num_workers=num_workers)

# %% ../nbs/02_dataloader.ipynb #675023e4
def pragma_dls(out, valid_pct=.2, max_tokens=max_tokens, mask=True, num_workers=0):
    out = Path(out)
    tok = Tokenizer.load(out/'tokenizer.json')
    trn,val = split_shards(sorted(out.glob('shard_*.parquet')), valid_pct)
    return tok,pragma_dl(trn, max_tokens, True, tok, mask, num_workers),pragma_dl(val, max_tokens, False, tok, mask, num_workers)

# %% ../nbs/02_dataloader.ipynb #ce9b7c45
batch_fields = 'profile profile_mask profile_time lifelong lifelong_mask lifelong_time event_tokens event_offsets event_user event_time cal history_offsets uids event_labels mlm_mask'.split()
special_toks = dict(usr='[USR]', evt='[EVT]')

def batch_shapes(b): return {k:(tuple(v.shape) if hasattr(v,'shape') else len(v)) for k,v in b.items()}

# %% ../nbs/02_dataloader.ipynb #a7c9486f
max_profile_toks,max_lifelong_toks,max_events,max_event_toks,max_tokens = 200,64,6500,24,12000
