"""Data loading, tokenization, and dataset assembly for fastpragma"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto #0
__all__ = ['SourceSchema', 'Tokenizer', 'PRAGMADataset']

# %% ../nbs/01_data.ipynb #35307cba
import polars as pl, numpy as np, torch, datetime
from dataclasses import dataclass, field
from collections import defaultdict
from fastcore.all import *

# %% ../nbs/01_data.ipynb #efd484bd
@dataclass
class SourceSchema:
    df: pl.DataFrame
    cats: list = field(default_factory=list)
    conts: list = field(default_factory=list)
    texts: list = field(default_factory=list)
    time_col: str = None
    lifelong: list = field(default_factory=list)
    num_buckets: int = 100
    cardinality_threshold: int = 100
    entity_col: str = 'entity_id'

    def __post_init__(self):
        named = set(self.cats + self.conts + self.texts + self.lifelong)
        if self.time_col: named.add(self.time_col)
        if self.entity_col: named.add(self.entity_col)
        for c in self.df.columns:
            if c in named: continue
            dt = self.df[c].dtype
            if dt in (pl.Float64, pl.Float32): self.conts.append(c)
            else: self.cats.append(c)

# %% ../nbs/01_data.ipynb #1cf6b7f2
def _parse_time(t):
    if t is None: return 0
    if hasattr(t, 'timestamp'): return int(t.timestamp())
    return int(t)

# %% ../nbs/01_data.ipynb #19219210
def _to_kvt(df, cats, conts, texts, time_col=None, lifelong=None):
    if lifelong is None: lifelong = []
    df_cols  = set(df.columns)
    cats     = [c for c in cats     if c in df_cols]
    conts    = [c for c in conts    if c in df_cols]
    texts    = [c for c in texts    if c in df_cols]
    lifelong = [c for c in lifelong if c in df_cols]
    cols = cats + conts + texts + lifelong
    if time_col: cols.append(time_col)
    df = df.select([c for c in cols if c in df.columns])
    rows = []
    for row in df.iter_rows(named=True):
        t = _parse_time(row.get(time_col)) if time_col else 0
        for c in cats:
            v = row.get(c); rows.append(dict(key=c, value=str(v) if v is not None else '', vtype='cat', time=t))
        for c in conts:
            v = row.get(c); rows.append(dict(key=c, value=float(v) if v is not None else 0.0, vtype='num', time=t))
        for c in texts:
            v = row.get(c); rows.append(dict(key=c, value=str(v) if v is not None else '', vtype='text', time=t))
        for c in lifelong:
            v = row.get(c)
            if v is not None:
                ts = v.timestamp() if hasattr(v, 'timestamp') else int(v)
                rows.append(dict(key=c, value='lifelong', vtype='cat', time=int(ts)))
    return rows

# %% ../nbs/01_data.ipynb #83b41024
class Tokenizer:
    def __init__(self, num_buckets=100, cardinality_threshold=100):
        self.num_buckets = num_buckets
        self.cardinality_threshold = cardinality_threshold
        self.key_vocab = {'[PAD]': 0, '[MASK]': 0, '[UNK]': 0}
        self.val_vocab = {'[PAD]': 0, '[MASK]': 0, '[UNK]': 0}
        self.num_bounds = {}

    def fit(self, sources):
        for src in sources:
            for c in src.cats:
                self._add_key(c)
                for v in src.df[c].unique().to_list():
                    self._add_val(str(v))
            for c in src.conts:
                self._add_key(c)
                vals = src.df[c].drop_nulls().to_numpy()
                if len(vals) == 0: vals = np.array([0.0])
                pcts = np.linspace(0, 100, self.num_buckets + 1)[1:]
                self.num_bounds[c] = np.percentile(vals, pcts)
            for c in src.texts:
                self._add_key(c)
                for v in src.df[c].drop_nulls().unique().to_list():
                    self._add_val(str(v))
            for c in src.lifelong:
                self._add_key(c)

    def _add_key(self, k):
        if k not in self.key_vocab: self.key_vocab[k] = len(self.key_vocab)

    def _add_val(self, v):
        if v not in self.val_vocab: self.val_vocab[v] = len(self.val_vocab)

    def tokenize(self, sources, max_events=512):
        all_keys = []; all_vals = []; all_times = []; all_masks = []
        for src in sources:
            kvt = _to_kvt(src.df, src.cats, src.conts, src.texts, src.time_col, src.lifelong)
            keys, vals, times = [], [], []
            for r in kvt:
                if r['key'] not in self.key_vocab: continue
                kid = self.key_vocab.get(r['key'], 0)
                if r['vtype'] == 'num':
                    bounds = self.num_bounds.get(r['key'], np.array([0]))
                    vid = int(np.searchsorted(bounds, r['value']))
                else:
                    vid = self.val_vocab.get(str(r['value']), 0)
                keys.append(kid); vals.append(vid); times.append(r['time'])
            n = len(keys)
            if n > max_events: keys, vals, times = keys[:max_events], vals[:max_events], times[:max_events]
            n = len(keys)
            all_keys.append(torch.tensor(keys, dtype=torch.long))
            all_vals.append(torch.tensor(vals, dtype=torch.long))
            all_times.append(torch.tensor(times, dtype=torch.float))
            all_masks.append(torch.ones(n, dtype=torch.bool))
        return dict(keys=all_keys, vals=all_vals, times=all_times, masks=all_masks)

# %% ../nbs/01_data.ipynb #e4b2279d
def _calendar_features(times):
    "Extract [hour, day_of_week, day_of_month] from Unix timestamps (seconds)."
    ts = times.long()
    hours = (ts // 3600) % 24
    days_of_week = (ts // 86400) % 7
    days_of_month = (ts // 86400) % 31 + 1
    return torch.stack([hours.float(), days_of_week.float(), days_of_month.float()], dim=-1)

# %% ../nbs/01_data.ipynb #c0001def
class PRAGMADataset:
    def __init__(self, static=None, dynamic=None, entity_col='entity_id',
                 max_events=512, max_profile_tokens=200, num_buckets=100):
        self.static = static
        self.dynamic = dynamic or []
        self.entity_col = entity_col
        self.max_events = max_events
        self.max_profile_tokens = max_profile_tokens
        self.tokenizer = Tokenizer(num_buckets=num_buckets)

    def tokenize(self):
        srcs = [s for s in [self.static] + self.dynamic if s is not None]
        self.tokenizer.fit(srcs)
        return {k: self._tokenize_entity(k) for k in self._all_entities()}

    def _all_entities(self):
        ids = set()
        if self.static: ids.update(self.static.df[self.entity_col].unique().to_list())
        for d in self.dynamic: ids.update(d.df[self.entity_col].unique().to_list())
        return sorted(ids)

    def _tokenize_entity(self, eid):
        ek = []; ev = []; et = []; em = []; epm = []
        if self.static:
            pdf = self.static.df.filter(pl.col(self.entity_col) == eid)
            if len(pdf):
                s = SourceSchema(pdf, cats=self.static.cats, conts=self.static.conts,
                    texts=self.static.texts, lifelong=self.static.lifelong,
                    num_buckets=self.static.num_buckets, entity_col=self.entity_col)
                t = self.tokenizer.tokenize([s], max_events=self.max_profile_tokens)
                n = t['keys'][0].shape[0]
                ek.append(t['keys'][0]); ev.append(t['vals'][0])
                et.append(t['times'][0]); em.append(t['masks'][0])
                epm.append(torch.ones(n, dtype=torch.bool))  # profile tokens
        for d in self.dynamic:
            edf = d.df.filter(pl.col(self.entity_col) == eid)
            if len(edf):
                s = SourceSchema(edf, cats=d.cats, conts=d.conts, texts=d.texts,
                    time_col=d.time_col, num_buckets=d.num_buckets,
                    lifelong=d.lifelong, entity_col=self.entity_col)
                t = self.tokenizer.tokenize([s], max_events=self.max_events)
                n = t['keys'][0].shape[0]
                ek.append(t['keys'][0]); ev.append(t['vals'][0])
                et.append(t['times'][0]); em.append(t['masks'][0])
                epm.append(torch.zeros(n, dtype=torch.bool))  # event tokens
        if ek:
            keys = torch.cat(ek); vals = torch.cat(ev)
            times = torch.cat(et); masks = torch.cat(em)
            profile_mask = torch.cat(epm)
            calendar = _calendar_features(times)
            return dict(keys=keys, vals=vals, times=times, masks=masks,
                       profile_mask=profile_mask, calendar=calendar)
        return dict(keys=torch.tensor([]), vals=torch.tensor([]),
                   times=torch.tensor([]), masks=torch.tensor([]),
                   profile_mask=torch.tensor([], dtype=torch.bool),
                   calendar=torch.tensor([]).reshape(0, 3))

    def show_batch(self, n=1):
        srcs = [s for s in [self.static] + self.dynamic if s is not None]
        if len(self.tokenizer.key_vocab) <= 3: self.tokenizer.fit(srcs)
        entities = self._all_entities()[:n]
        for eid in entities:
            tok = self._tokenize_entity(eid)
            print(f'Entity {eid}: {tok["keys"].shape[0]} tokens')
            if self.static:
                pdf = self.static.df.filter(pl.col(self.entity_col) == eid)
                if len(pdf):
                    print('  Profile:')
                    for c in self.static.cats:
                        print(f'    {c}={pdf[c][0]} (categorical)')
                    for c in self.static.conts:
                        print(f'    {c}={pdf[c][0]} (numerical)')
            for d in self.dynamic:
                edf = d.df.filter(pl.col(self.entity_col) == eid)
                if len(edf):
                    print(f'  Events ({d.time_col}): {len(edf)} rows')
                    for row in edf.head(3).iter_rows(named=True):
                        parts = [f'{k}={row[k]}' for k in d.cats + d.conts[:2]]
                        print(f'    [{row[d.time_col]}] {", ".join(parts)}')
