"""Encoder-only Transformer backbone for PRAGMA"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_model.ipynb.

# %% auto #0
__all__ = ['ARCH', 'TransformerBlock', 'RoPE', 'PRAGMA']

# %% ../nbs/02_model.ipynb #6ac2db20
import torch, torch.nn as nn, torch.nn.functional as F
from dataclasses import dataclass
import math
from fastcore.all import *

# %% ../nbs/02_model.ipynb #d397ea32
    # PRAGMA model family (paper Table 1). Scales width (d_model, d_ffn) and depth
    # of all three encoders. n_profile/n_event/n_history = number of TransformerBlock
    # layers in each encoder. n_heads = attention heads (must divide d_model).
ARCH = {
    's': dict(d_model=192, d_ffn=768,  n_heads=3,  n_profile=1, n_event=5,  n_history=2),  # 10M params (with full vocab)
    'm': dict(d_model=512, d_ffn=2048, n_heads=8,  n_profile=3, n_event=16, n_history=6),  # 100M params
    'l': dict(d_model=1024,d_ffn=4096, n_heads=16, n_profile=9, n_event=45, n_history=18),  # 1B params
}

# %% ../nbs/02_model.ipynb #f48c7790
class TransformerBlock(nn.Module):
    """Pre-norm Transformer block with GELU activation and dropout (paper §2.3.1).
    Uses residual connections: x = x + sublayer(norm(x))."""
    def __init__(self, d_model, d_ffn, n_heads=8, dropout=0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(d_model)  # pre-norm before attention
        self.attn = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
        self.norm2 = nn.LayerNorm(d_model)  # pre-norm before MLP
        self.mlp = nn.Sequential(  # FFN: expand → GELU → project back
            nn.Linear(d_model, d_ffn), nn.GELU(), nn.Dropout(dropout),
            nn.Linear(d_ffn, d_model), nn.Dropout(dropout))

    def forward(self, x, mask=None):
        # Pre-norm residual: x + sublayer(norm(x)). mask = key_padding_mask (True = padding).
        x = x + self.attn(self.norm1(x), self.norm1(x), self.norm1(x), key_padding_mask=mask)[0]
        x = x + self.mlp(self.norm2(x))
        return x

# %% ../nbs/02_model.ipynb #77ca43b8
class RoPE(nn.Module):
    """Rotary Position Embedding (Su et al., 2024). Encodes temporal position by
    rotating pairs of dimensions in the embedding space. Used for time-to-last-event
    and time-since-lifelong-events encoding in the Profile State and History encoders."""
    def __init__(self, d_model, max_len=10000):
        super().__init__()
        # Inverse frequency: theta_i = 1/10000^(2i/d) for i in 0, 2, 4, ..., d-2
        theta = 1.0 / (10000 ** (torch.arange(0, d_model, 2).float() / d_model))
        self.register_buffer('theta', theta)

    def forward(self, x, times):
        # x: (B, L, D), times: (B, L) — time values (already log-scaled by caller)
        B, L, D = x.shape
        pos = times.unsqueeze(-1) * self.theta  # (B, L, D/2) angular frequencies
        cos, sin = pos.cos(), pos.sin()
        # Split into even/odd dimension pairs and apply 2D rotation
        x_even, x_odd = x[..., 0::2], x[..., 1::2]
        # stack + flatten preserves interleaved layout (unlike cat which gives half-split)
        return torch.stack([
            x_even * cos - x_odd * sin,
            x_odd  * cos + x_even * sin
        ], dim=-1).flatten(-2)

# %% ../nbs/02_model.ipynb #68894394
class PRAGMA(nn.Module):
    """PRAGMA encoder-only backbone (paper §2.3). Three-block architecture:
    Profile State Encoder → Event Encoder → History Encoder.

    Args:
        d_model: hidden dimension. d_ffn: FFN inner dimension (typically 4x d_model).
        n_heads: attention heads. n_profile/n_event/n_history: depth of each encoder.
        n_keys/n_vals: vocabulary sizes for key and value embeddings.
        dropout: dropout rate (paper uses 0.1).
    """
    def __init__(self, d_model=192, d_ffn=768, n_heads=3, n_profile=1, n_event=5, n_history=2,
                 n_keys=64, n_vals=1024, dropout=0.1):
        super().__init__()
        self.d_model = d_model
        # Token embeddings: key (field name) + value (field value) are summed
        self.key_emb = nn.Embedding(n_keys, d_model)
        self.val_emb = nn.Embedding(n_vals, d_model)
        self.rope = RoPE(d_model)
        # Three encoder blocks, each a stack of TransformerBlocks
        self.profile_enc = nn.ModuleList([TransformerBlock(d_model, d_ffn, n_heads, dropout) for _ in range(n_profile)])
        self.event_enc   = nn.ModuleList([TransformerBlock(d_model, d_ffn, n_heads, dropout) for _ in range(n_event)])
        self.history_enc = nn.ModuleList([TransformerBlock(d_model, d_ffn, n_heads, dropout) for _ in range(n_history)])
        # Learnable special tokens prepended to sequences (paper §2.3.2–2.3.3)
        self.usr_token  = nn.Parameter(torch.randn(1, 1, d_model))  # [USR] for profile state
        self.evt_token  = nn.Parameter(torch.randn(1, 1, d_model))  # [EVT] for each event
        # Calendar feature MLP: [hour, day_of_week, day_of_month] → d_model (paper §2.3.3)
        self.cal_mlp = nn.Sequential(nn.Linear(3, d_model), nn.GELU(), nn.Linear(d_model, d_model))
        # MLM head: concat[event_enc, history, history[USR]] (3*d_model) → n_vals logits (paper §2.3.5)
        self.mlm_head = nn.Sequential(nn.Linear(d_model * 3, d_model), nn.GELU(), nn.Linear(d_model, n_vals))

    def forward(self, keys, vals, times, masks=None, profile_mask=None, calendar=None, return_mlm=False):
        B = keys.shape[0]
        x = self.key_emb(keys) + self.val_emb(vals)  # (B, L, D)
        times_enc = torch.log1p(times / 8) * 8

        if profile_mask is None:
            # Simplified path: event → history (backward compatible)
            x = self.rope(x, times_enc)
            for blk in self.event_enc: x = blk(x, masks)
            for blk in self.history_enc: x = blk(x, masks)
            return x

        # Three-block architecture (paper §2.3)
        # Profile State Encoder: [USR] + tokens, RoPE on time-since-lifelong-events (§2.3.2)
        usr = self.usr_token.expand(B, -1, -1)
        prof_times = torch.cat([torch.zeros(B, 1, device=times.device), times_enc], dim=1)
        x_prof = self.rope(torch.cat([usr, x], dim=1), prof_times)
        prof_kpm = torch.cat([torch.zeros(B, 1, dtype=torch.bool, device=profile_mask.device), ~profile_mask], dim=1)
        for blk in self.profile_enc: x_prof = blk(x_prof, prof_kpm)
        usr_emb = x_prof[:, 0:1, :]  # [USR] embedding za

        # Event Encoder: [EVT] + tokens, RoPE + calendar features (§2.3.3)
        evt = self.evt_token.expand(B, -1, -1)
        evt_times = torch.cat([torch.zeros(B, 1, device=times.device), times_enc], dim=1)
        x_evt = self.rope(torch.cat([evt, x], dim=1), evt_times)
        evt_kpm = torch.cat([torch.zeros(B, 1, dtype=torch.bool, device=profile_mask.device), profile_mask], dim=1)
        for blk in self.event_enc: x_evt = blk(x_evt, evt_kpm)
        if calendar is not None:
            cal_full = torch.cat([torch.zeros(B, 1, calendar.shape[-1], device=calendar.device), calendar], dim=1)
            cal_mask = torch.cat([torch.zeros(B, 1, 1, device=profile_mask.device), (~profile_mask).unsqueeze(-1).float()], dim=1)
            x_evt = x_evt + self.cal_mlp(cal_full) * cal_mask

        # History Encoder: [USR] + [EVT] + event tokens, RoPE on time-to-last-event (§2.3.4)
        hist_in = torch.cat([usr_emb, x_evt], dim=1)  # (B, 2+L, D)
        hist_times = torch.cat([torch.zeros(B, 2, device=times.device), times_enc], dim=1)
        hist_in = self.rope(hist_in, hist_times)
        hist_mask = torch.cat([torch.zeros(B, 2, dtype=torch.bool, device=masks.device), masks], dim=1) if masks is not None else None
        for blk in self.history_enc: hist_in = blk(hist_in, hist_mask)

        if return_mlm:
            # MLM head: concat [event_enc data, history data, history [USR]] (§2.3.5)
            x_evt_data = x_evt[:, 1:, :]  # event data token outputs (B, L, D)
            hist_data = hist_in[:, 2:, :]  # history data token outputs (B, L, D)
            usr_hist = hist_in[:, 0:1, :].expand(-1, x_evt_data.shape[1], -1)
            logits = self.mlm_head(torch.cat([x_evt_data, hist_data, usr_hist], dim=-1))
            return hist_in, logits
        return hist_in

    def embed(self, dataset, pool='both'):
        """Extract embeddings for all entities in a PRAGMADataset.
        pool: 'first' = [USR] position, 'last' = last real token, 'both' = mean pool."""
        tok = dataset.tokenize()
        embs = {}
        self.eval()
        with torch.no_grad():
            for eid, t in tok.items():
                if t['keys'].numel() == 0: embs[eid] = torch.zeros(self.d_model); continue
                k = t['keys'].unsqueeze(0); v = t['vals'].unsqueeze(0)
                ti = t['times'].unsqueeze(0)
                # masks in tokenized data: True = real token → invert for key_padding_mask
                m = (~t['masks']).unsqueeze(0) if t['masks'].numel() else None
                pm = t['profile_mask'].unsqueeze(0) if 'profile_mask' in t else None
                cal = t['calendar'].unsqueeze(0) if 'calendar' in t else None
                h = self(k, v, ti, m, pm, cal)  # (1, L, D) or (1, 2+L, D) with [USR]+[EVT]
                if pool == 'first': e = h[:, 0, :]  # [USR] position
                elif pool == 'last':
                    lens = t['masks'].sum() if t['masks'].numel() else h.shape[1]
                    offset = 2 if pm is not None else 0  # [USR]+[EVT] prepended in three-block
                    e = h[:, offset + lens - 1, :]
                else: e = h.mean(dim=1)
                embs[eid] = e.squeeze(0)
        return embs

    def embed_record(self, record):
        """Embed a single tokenized record (dict with keys/vals/times/masks/etc).
        Returns a (d_model,) vector via mean pooling over all output positions."""
        k, v, t = record['keys'], record['vals'], record['times']
        if k.numel() == 0: return torch.zeros(self.d_model)
        self.eval()
        with torch.no_grad():
            pm = record['profile_mask'].unsqueeze(0) if 'profile_mask' in record else None
            cal = record['calendar'].unsqueeze(0) if 'calendar' in record else None
            h = self(k.unsqueeze(0), v.unsqueeze(0), t.unsqueeze(0), profile_mask=pm, calendar=cal)
            return h.mean(dim=1).squeeze(0)

    @classmethod
    def load(cls, size='s'):
        """Instantiate from a named architecture variant ('s', 'm', or 'l')."""
        cfg = ARCH[size]
        return cls(**cfg)
