# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_model.ipynb.

# %% auto #0
__all__ = ['KVEmb', 'prepend_tok', 'RotaryEmb', 'rotate_half', 'apply_rope', 'rope_apply', 'RopeMHA', 'EncoderLayer', 'Encoder',
           'ProfileEncoder', 'pad_packed', 'cu_seqlens', 'has_flash_attn', 'lens_from_offsets', 'VarlenMHA',
           'VarlenEncoderLayer', 'VarlenEncoder', 'prepend_packed_tok', 'EventEncoder', 'CalEmb', 'pad_history',
           'HistoryEncoder', 'MLMHead', 'token_event_ids', 'token_user_ids', 'PRAGMAModel', 'mlm_loss',
           'FastaiPRAGMADL', 'fastai_pragma_dl', 'PRAGMAWrapper', 'pragma_loss', 'pragma_dls', 'pragma_learner']

# %% ../nbs/03_model.ipynb #b3c40a92
import torch
from torch import nn
from torch.nn.utils.rnn import pad_sequence
from fastcore.all import *
from .dataloader import pragma_dl
from .data import Tokenizer, PRAGMADataset

# %% ../nbs/03_model.ipynb #ce49fac0
class KVEmb(nn.Module):
    "Embed key, value, and value-position triples"
    def __init__(self, n_keys, n_vals, d_model, max_val_pos=32):
        super().__init__()
        store_attr()
        self.key_emb,self.val_emb,self.pos_emb = nn.Embedding(n_keys, d_model),nn.Embedding(n_vals, d_model),nn.Embedding(max_val_pos, d_model)

    def forward(self, x):
        k,v,p = x[...,0],x[...,1],x[...,2].clamp_max(self.max_val_pos-1)
        return self.key_emb(k) + self.val_emb(v) + self.pos_emb(p)

# %% ../nbs/03_model.ipynb #254af7af
def prepend_tok(x, tok):
    "Prepend one learned token to each batch item"
    return torch.cat([tok.expand(x.shape[0], 1, -1), x], 1)

# %% ../nbs/03_model.ipynb #8c6e2710
class RotaryEmb(nn.Module):
    "Rotary positional embedding"
    def __init__(self, dim, base=10000):
        super().__init__()
        inv_freq = 1. / (base ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer('inv_freq', inv_freq, persistent=False)

    def forward(self, pos):
        freqs = pos.float()[...,None] * self.inv_freq
        return freqs.cos(),freqs.sin()

def rotate_half(x):
    x1,x2 = x[...,::2],x[...,1::2]
    return torch.stack([-x2,x1], -1).flatten(-2)

def apply_rope(x, cos, sin):
    cos,sin = cos.repeat_interleave(2, -1),sin.repeat_interleave(2, -1)
    return x*cos + rotate_half(x)*sin

#| export
def rope_apply(q, k, rope_emb, pos):
    cos,sin = rope_emb(pos)
    if cos.ndim == 2: cos,sin = cos[None,None],sin[None,None]
    else: cos,sin = cos[:,None],sin[:,None]
    return apply_rope(q, cos, sin),apply_rope(k, cos, sin)

# %% ../nbs/03_model.ipynb #d8e8bd5e
class RopeMHA(nn.Module):
    "Multi-head attention with optional RoPE"
    def __init__(self, d_model, n_heads=4, p=0.1, rope=False):
        super().__init__()
        store_attr()
        self.qkv,self.proj,self.drop = nn.Linear(d_model, d_model*3),nn.Linear(d_model, d_model),nn.Dropout(p)
        self.rope_emb = RotaryEmb(d_model//n_heads) if rope else None

    def forward(self, x, mask=None, pos=None):
        bs,sl,_ = x.shape
        q,k,v = self.qkv(x).chunk(3, -1)
        q,k,v = [o.view(bs, sl, self.n_heads, -1).transpose(1, 2) for o in (q,k,v)]
        if self.rope_emb is not None:
            pos = ifnone(pos, torch.arange(sl, device=x.device))
            q,k = rope_apply(q, k, self.rope_emb, pos)
        attn_mask = None if mask is None else mask.bool()[:,None,None]
        y = nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask, dropout_p=self.p if self.training else 0.)
        return self.proj(y.transpose(1, 2).contiguous().view(bs, sl, -1))

class EncoderLayer(nn.Module):
    "Pre-norm Transformer encoder layer"
    def __init__(self, d_model, n_heads=4, d_ff=None, p=0.1, rope=False):
        super().__init__()
        d_ff = ifnone(d_ff, d_model*4)
        self.attn,self.ln1,self.ln2,self.drop = RopeMHA(d_model, n_heads, p, rope),nn.LayerNorm(d_model),nn.LayerNorm(d_model),nn.Dropout(p)
        self.ff = nn.Sequential(nn.Linear(d_model, d_ff), nn.GELU(), nn.Dropout(p), nn.Linear(d_ff, d_model))

    def forward(self, x, mask=None, pos=None):
        x = x + self.drop(self.attn(self.ln1(x), mask, pos))
        return x + self.drop(self.ff(self.ln2(x)))

class Encoder(nn.Module):
    "Small Transformer encoder wrapper"
    def __init__(self, d_model, n_heads=4, n_layers=2, d_ff=None, p=0.1, rope=False):
        super().__init__()
        self.layers = nn.ModuleList([EncoderLayer(d_model, n_heads, d_ff, p, rope) for _ in range(n_layers)])

    def forward(self, x, mask=None, pos=None):
        for l in self.layers: x = l(x, mask, pos)
        return x

# %% ../nbs/03_model.ipynb #da3b46cd
class ProfileEncoder(nn.Module):
    "Encode profile and lifelong tokens into one user vector"
    def __init__(self, n_keys, n_vals, d_model, n_heads=4, n_layers=2):
        super().__init__()
        self.emb = KVEmb(n_keys, n_vals, d_model)
        self.usr = nn.Parameter(torch.randn(1, 1, d_model)*0.02)
        self.enc = Encoder(d_model, n_heads, n_layers, rope=True)

    def forward(self, profile, profile_mask, profile_time=None, lifelong=None, lifelong_mask=None, lifelong_time=None):
        x,mask = self.emb(profile),profile_mask.bool()
        t = torch.zeros_like(profile_mask, dtype=torch.float) if profile_time is None else profile_time.float()
        if lifelong is not None:
            x = torch.cat([x, self.emb(lifelong)], 1)
            mask = torch.cat([mask, lifelong_mask.bool()], 1)
            lt = torch.zeros_like(lifelong_mask, dtype=torch.float) if lifelong_time is None else lifelong_time.float()
            t = torch.cat([t, lt], 1)
        x = prepend_tok(x, self.usr)
        mask = torch.cat([torch.ones(mask.shape[0], 1, device=mask.device, dtype=torch.bool), mask], 1)
        t = torch.cat([torch.zeros(t.shape[0], 1, device=t.device), t], 1)
        return self.enc(x, mask, t)[:,0]

# %% ../nbs/03_model.ipynb #6ced49a2
def pad_packed(x, offsets):
    "Pad packed rows using offsets"
    xs = [x[s:e] for s,e in zip(offsets[:-1], offsets[1:])]
    return nn.utils.rnn.pad_sequence(xs, batch_first=True),torch.tensor([len(o) for o in xs], device=x.device)

# %% ../nbs/03_model.ipynb #739b2a26
try: from flash_attn.flash_attn_interface import flash_attn_varlen_qkvpacked_func
except Exception: flash_attn_varlen_qkvpacked_func = None

# %% ../nbs/03_model.ipynb #f89a7446
def cu_seqlens(offsets): return offsets.to(torch.int32)
def has_flash_attn(): return flash_attn_varlen_qkvpacked_func is not None and torch.cuda.is_available()

# %% ../nbs/03_model.ipynb #788bf5f8
def lens_from_offsets(offsets): return offsets[1:] - offsets[:-1]

# %% ../nbs/03_model.ipynb #85b0d643
class VarlenMHA(nn.Module):
    "Packed multi-head attention with padded fallback"
    def __init__(self, d_model, n_heads=4, p=0.1):
        super().__init__()
        store_attr()
        self.qkv,self.proj = nn.Linear(d_model, d_model*3),nn.Linear(d_model, d_model)

    def forward(self, x, offsets):
        if has_flash_attn(): return self._flash(x, offsets)
        return self._padded(x, offsets)

    def _flash(self, x, offsets):
        qkv = self.qkv(x).view(x.shape[0], 3, self.n_heads, -1)
        y = flash_attn_varlen_qkvpacked_func(qkv, cu_seqlens(offsets), int(lens_from_offsets(offsets).max()), dropout_p=self.p if self.training else 0.)
        return self.proj(y.reshape(x.shape[0], -1))

    def _padded(self, x, offsets):
        xp,lens = pad_packed(x, offsets)
        bs,sl,_ = xp.shape
        q,k,v = self.qkv(xp).chunk(3, -1)
        q,k,v = [o.view(bs, sl, self.n_heads, -1).transpose(1, 2) for o in (q,k,v)]
        mask = torch.arange(sl, device=x.device)[None] < lens[:,None]
        y = nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask[:,None,None], dropout_p=self.p if self.training else 0.)
        y = self.proj(y.transpose(1, 2).contiguous().view(bs, sl, -1))
        return torch.cat([y[i,:l] for i,l in enumerate(lens)])

# %% ../nbs/03_model.ipynb #0099b626
class VarlenEncoderLayer(nn.Module):
    "Pre-norm packed Transformer encoder layer"
    def __init__(self, d_model, n_heads=4, d_ff=None, p=0.1):
        super().__init__()
        d_ff = ifnone(d_ff, d_model*4)
        self.attn,self.ln1,self.ln2,self.drop = VarlenMHA(d_model, n_heads, p),nn.LayerNorm(d_model),nn.LayerNorm(d_model),nn.Dropout(p)
        self.ff = nn.Sequential(nn.Linear(d_model, d_ff), nn.GELU(), nn.Dropout(p), nn.Linear(d_ff, d_model))

    def forward(self, x, offsets):
        x = x + self.drop(self.attn(self.ln1(x), offsets))
        return x + self.drop(self.ff(self.ln2(x)))

class VarlenEncoder(nn.Module):
    "Packed Transformer encoder wrapper"
    def __init__(self, d_model, n_heads=4, n_layers=2, d_ff=None, p=0.1):
        super().__init__()
        self.layers = nn.ModuleList([VarlenEncoderLayer(d_model, n_heads, d_ff, p) for _ in range(n_layers)])

    def forward(self, x, offsets):
        for l in self.layers: x = l(x, offsets)
        return x

# %% ../nbs/03_model.ipynb #d5e062f9
def prepend_packed_tok(x, offsets, tok):
    "Prepend one learned token to each packed sequence"
    xs = [torch.cat([tok[0], x[s:e]]) for s,e in zip(offsets[:-1], offsets[1:])]
    return torch.cat(xs),torch.cat([offsets.new_tensor([0]), torch.tensor([len(o) for o in xs], device=offsets.device).cumsum(0)])

# %% ../nbs/03_model.ipynb #cd55d408
class EventEncoder(nn.Module):
    "Encode packed event tokens into event and token representations"
    def __init__(self, n_keys, n_vals, d_model, n_heads=4, n_layers=2):
        super().__init__()
        self.emb = KVEmb(n_keys, n_vals, d_model)
        self.evt = nn.Parameter(torch.randn(1, 1, d_model)*0.02)
        self.enc = VarlenEncoder(d_model, n_heads, n_layers)

    def forward(self, event_tokens, event_offsets):
        x,offs = prepend_packed_tok(self.emb(event_tokens), event_offsets, self.evt)
        h = self.enc(x, offs)
        lens = lens_from_offsets(offs)
        evt = h[offs[:-1]]
        tok = torch.cat([h[s+1:e] for s,e in zip(offs[:-1], offs[1:])])
        return evt,tok

# %% ../nbs/03_model.ipynb #948e8c11
class CalEmb(nn.Module):
    "Embed event calendar features"
    def __init__(self, n_cal, d_model):
        super().__init__()
        self.mlp = nn.Sequential(nn.Linear(n_cal, d_model), nn.GELU(), nn.Linear(d_model, d_model))

    def forward(self, x): return self.mlp(x.float())

# %% ../nbs/03_model.ipynb #33464229
def pad_history(z_usr, z_evt, event_time, history_offsets):
    "Build padded user histories and history times"
    xs = [torch.cat([z_usr[i][None], z_evt[s:e]]) for i,(s,e) in enumerate(zip(history_offsets[:-1], history_offsets[1:]))]
    ts = [torch.cat([event_time.new_zeros(1), event_time[s:e].float()]) for s,e in zip(history_offsets[:-1], history_offsets[1:])]
    return pad_sequence(xs, batch_first=True),torch.tensor([len(o) for o in xs], device=z_evt.device),pad_sequence(ts, batch_first=True)

# %% ../nbs/03_model.ipynb #d9cd204b
class HistoryEncoder(nn.Module):
    "Contextualize user histories"
    def __init__(self, d_model, n_heads=4, n_layers=2):
        super().__init__()
        self.enc = Encoder(d_model, n_heads, n_layers, rope=True)

    def forward(self, z_usr, z_evt, event_user, history_offsets, event_time):
        x,lens,pos = pad_history(z_usr, z_evt, event_time, history_offsets)
        mask = torch.arange(x.shape[1], device=x.device)[None] < lens[:,None]
        h = self.enc(x, mask, pos)
        return h[:,0],torch.cat([h[i,1:l] for i,l in enumerate(lens)])

# %% ../nbs/03_model.ipynb #7a8b4ebc
class MLMHead(nn.Module):
    "Predict masked event value tokens"
    def __init__(self, d_model, n_vals):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(d_model*3, d_model), nn.GELU(), nn.Linear(d_model, n_vals))

    def forward(self, tok_h, evt_h, usr_h): return self.net(torch.cat([tok_h, evt_h, usr_h], -1))

# %% ../nbs/03_model.ipynb #3999f486
def token_event_ids(event_offsets):
    "Map packed event tokens to event ids"
    lens = event_offsets[1:] - event_offsets[:-1]
    return torch.repeat_interleave(torch.arange(len(lens), device=event_offsets.device), lens)

# %% ../nbs/03_model.ipynb #7f19c928
def token_user_ids(event_offsets, event_user):
    "Map packed event tokens to user ids"
    return event_user[token_event_ids(event_offsets)]

# %% ../nbs/03_model.ipynb #8983dd53
class PRAGMAModel(nn.Module):
    "Small PRAGMA-style encoder"
    def __init__(self, n_keys, n_vals, d_model=128, n_heads=4, n_layers=2, n_cal=3):
        super().__init__()
        store_attr()
        self.profile_enc = ProfileEncoder(n_keys, n_vals, d_model, n_heads, n_layers)
        self.event_enc = EventEncoder(n_keys, n_vals, d_model, n_heads, n_layers)
        self.cal_emb = CalEmb(n_cal, d_model)
        self.history_enc = HistoryEncoder(d_model, n_heads, n_layers)
        self.mlm = MLMHead(d_model, n_vals)

    def forward(self, b):
        z_usr = self.profile_enc(b['profile'], b['profile_mask'], b.get('profile_time'), b.get('lifelong'), b.get('lifelong_mask'), b.get('lifelong_time'))
        z_evt,tok_h = self.event_enc(b['event_tokens'], b['event_offsets'])
        
        z_evt = z_evt + self.cal_emb(b['cal'])
        h_usr,h_evt = self.history_enc(z_usr, z_evt, b['event_user'], b['history_offsets'], b['event_time'])
        tok_evt,tok_usr = token_event_ids(b['event_offsets']),token_user_ids(b['event_offsets'], b['event_user'])
        m = b['mlm_mask'].bool()
        logits = self.mlm(tok_h[m], h_evt[tok_evt[m]], h_usr[tok_usr[m]])
        return dict(h_usr=h_usr, h_evt=h_evt, logits=logits, labels=b['event_labels'][m])

# %% ../nbs/03_model.ipynb #c83e06d4
def mlm_loss(out): return nn.functional.cross_entropy(out['logits'], out['labels'])

# %% ../nbs/03_model.ipynb #e372dc42
import fastpragma.dataloader as fdl
from fastai.callback.core import Callback, CancelEpochException
from fastai.data.core import DataLoaders
from fastai.learner import Learner
from fastai.optimizer import Adam
from .dataloader import PRAGMADataLoader

# %% ../nbs/03_model.ipynb #b9e3da38
class FastaiPRAGMADL:
    "Wrap PRAGMA batches as fastai input-target pairs"
    def __init__(self, dl): self.dl = dl
    def __iter__(self):
        for b in self.dl: yield b,b
    def __len__(self): return len(self.dl)

def fastai_pragma_dl(*args, **kwargs): return FastaiPRAGMADL(pragma_dl(*args, **kwargs))

# %% ../nbs/03_model.ipynb #fd843379
class PRAGMAWrapper(nn.Module):
    "Return MLM logits"
    def __init__(self, model): super().__init__(); self.model = model
    def forward(self, b): return self.model(b)['logits']

def pragma_loss(logits, b): return nn.functional.cross_entropy(logits, b['event_labels'][b['mlm_mask'].bool()])

# %% ../nbs/03_model.ipynb #1804e5cc
def pragma_dls(shards, tok, max_tokens=1500):
    train_dl = fastai_pragma_dl(shards, max_tokens=max_tokens, shuffle=True, mask=True, tok=tok)
    valid_dl = fastai_pragma_dl(shards[:1], max_tokens=max_tokens, shuffle=False, mask=True, tok=tok)
    return DataLoaders(train_dl, valid_dl)

def pragma_learner(dls, n_keys, n_vals, d_model=32, n_heads=2, n_layers=1, opt_func=Adam):
    m = PRAGMAModel(n_keys, n_vals, d_model=d_model, n_heads=n_heads, n_layers=n_layers)
    return Learner(dls, PRAGMAWrapper(m), loss_func=pragma_loss, opt_func=opt_func)
